CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'USER ID',
  `name` VARCHAR(50) NOT NULL COMMENT 'USER NAME',
  `email` VARCHAR(255) NOT NULL COMMENT 'EMAIL ADDRESS',
  `password` VARCHAR(255) NOT NULL COMMENT 'USER PASSWORD',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE OF CREATION',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE OF UPDATE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_unq` (`email` ASC))
COMMENT = 'USERS TABLE';
